<a href="https://colab.research.google.com/github/Adriandzidan/Tugas-Kecerdasan-Buatan/blob/main/Jobsheet02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LATIHAN**

**A. tipe data phython**

1. Cek Tipe Data

In [1]:
# Cek tipe data
var = 123
print(type(var))

<class 'int'>


2. Tipe data String

In [3]:
# String
a = '123'
b = '3.4'
c = "Data String"
print(type(c))


<class 'str'>


3. Tipe data numerik

In [2]:
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)

sum = var1 + var2
print(sum)

var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)


<class 'float'>
345.0
379.5
34
12


4.	Tipe Data Boolean

In [4]:
# Boolean
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

False
False
True
True


5.	Tipe Data List

In [5]:
data = ["belajar dasar python", 2023, 3.8, True]
print(data)
print(data[3])
print(data[1:3])
print(len(data))

['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


**B.Operasi matematika menggunakan python**

In [7]:
import math

# min & max
x = min(5, 10, 25)
y = max(6, 12, 18)

# absolut
a = abs(-7.25)

# pangkat
b = math.pow(4, 3)

# akar
c = math.sqrt(64)

# pembulatan
d = math.ceil(1.4)
e = math.floor(1.4)

# pi
f = math.pi

C. Menggunakan Fungsi MATH

In [8]:
import numpy as np

# Matriks
A = np.array([[80, 30, 25],
              [50, 20, 10]])

B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B
print(hasil)

# Dot product
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)

# Cross product
hasil = np.cross(A, B)
print(hasil)

[[110  90  40]
 [ 60  50  40]]
2025
[-305 -110  350]


**D.	Operasi matriks dan vektor dengan python**

In [9]:
import numpy as np

# Matriks
A = np.array([[80, 30, 25],
              [50, 20, 10]])

B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B
print(hasil)

# Dot product
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)

# Cross product
hasil = np.cross(A, B)
print(hasil)

[[110  90  40]
 [ 60  50  40]]
2025
[-305 -110  350]


# **TUGAS PRAKTIKUM**

**1. Tentukan hasil perkalian berikut menggunakan kode python**

In [11]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.array([[1, 0],
              [0, 1]])

hasil1 = np.dot(A, B)
hasil2 = np.dot(B, C)

print("A x B =")
print(hasil1)

print("B x C =")
print(hasil2)

A x B =
[[19 22]
 [43 50]]
B x C =
[[5 6]
 [7 8]]


**2.	Hitunglah nilai dari soal faktorial berikut**

In [14]:
# A.6!
import math
print(math.factorial(6))

#B. 8! / 5!
hasil = math.factorial(8) / math.factorial(5)
print(hasil)

720
336.0


**3.	Dua Buah Vektor A dan B merupakan vektor 3D pada koordinat kartesian. Jika Vektor A = 5i + 3j + 7k dan Vektor B = 12i – 3j + k. Maka tentukan panjang masing-masing Vektor, hasil perkalian titik A.B, dan AxB.**

In [21]:
import numpy as np

print("Panjang Vektor")
#Panjang Vektor
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

print(panjang_A)
print(panjang_B)

print("Dot Product")
#B. Dot Prodyct
dot = np.dot(A, B)
print(dot)

print("Cross Product")
#Cross Product (A x B)
cross = np.cross(A, B)
print(cross)

Panjang Vektor
9.1104335791443
12.409673645990857
Dot Product
58
Cross Product
[ 24  79 -51]
